# Generated by Django 5.1.15 on 2026-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('specializzazione', models.CharField(blank=True, max_length=50)),
                ('id_operatore', models.BigAutoField(primary_key=True, serialize=False)),
                ('turno_inizio', models.TimeField(blank=True, null=True)),
                ('turno_fine', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segnalazioni',
            fields=[
                ('id_richiesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('azione_intrapresa', models.CharField(max_length=20)),
                ('esito', models.CharField(max_length=20)),
                ('note_riservate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('tipo_violenza', models.CharField(choices=[('fisica', 'fisica'), ('psicologica', 'psicologica'), ('stalking', 'stalking')], max_length=15)),
                ('descrizione', models.CharField(max_length=500)),
                ('livello_urgenza', models.IntegerField()),
                ('stato_richiesta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_utente', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
                ('regione_provenienza', models.CharField(max_length=20)),
                ('fascia_eta', models.CharField(choices=[('-18', 'Minorenne'), ('18-29', '18-29'), ('30-49', '30-49'), ('50-70', '50-70'), ('70+', '70+')], max_length=5)),
            ],
        ),
    ]
