# Generated by Django 5.2.11 on 2026-02-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
