# Generated by Django 5.2.11 on 2026-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0002_alter_utente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='fascia_eta',
            field=models.CharField(choices=[('-18', 'Minorenne'), ('18-29', '18-29'), ('30-49', '30-49'), ('50-70', '50-70'), ('70+', '70+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='utente',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
