# Generated by Django 5.2.11 on 2026-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0003_alter_utente_fascia_eta_alter_utente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
