# Generated by Django 5.2.11 on 2026-03-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0004_alter_utente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='password',
        ),
    ]
