# Generated by Django 5.2.11 on 2026-03-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0005_remove_utente_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fascia_eta',
            field=models.CharField(blank=True, choices=[('-18', 'Minorenne'), ('18-29', '18-29'), ('30-49', '30-49'), ('50-70', '50-70'), ('70+', '70+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nome_utente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='regione_provenienza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='livello_urgenza',
            field=models.IntegerField(choices=[('low', 'Basso'), ('medium', 'Medio'), ('high', 'Alto')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
