# Generated by Django 5.2.11 on 2026-03-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0006_delete_utente_ticket_email_ticket_fascia_eta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='regione_provenienza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
