# Generated by Django 5.2.11 on 2026-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appantiviolenza', '0007_alter_ticket_regione_provenienza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='livello_urgenza',
            field=models.CharField(choices=[('low', 'Basso'), ('medium', 'Medio'), ('high', 'Alto')], max_length=40),
        ),
    ]
